services:
  - type: worker
    name: smoobu-bot
    runtime: docker       # ← required for using dockerfilePath
    dockerfilePath: ./Dockerfile
    plan: starter
    autoDeploy: false
    disk:
      name: smoobu-data
      mountPath: /mnt/data
      sizeGB: 1
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_ASSISTANT_ID
        sync: false
      - key: SMOOBU_API_KEY
        sync: false
