services:
  - type: web
    name: smoobu-scheduler
    dockerfilePath: ./Dockerfile
    plan: starter
    autoDeploy: false
    disk:
      name: smoobu-data
      mountPath: /mnt/data
      sizeGB: 1
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SMOOBU_API_KEY
        sync: false
